const fs = require('fs');
const path = require('path');
const out = 'public';
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const rootFiles = ['index.html','style.css','logo-picotrack.png','manifest.json','favicon.ico','sw.js','robots.txt','security.txt','BUILD_INFO.json'];
for (const f of rootFiles) if (fs.existsSync(f)) fs.copyFileSync(f, path.join(out, f));
if (!fs.existsSync('public.html')) throw new Error('public.html manquant : le portail public doit être publié');
fs.copyFileSync('public.html', path.join(out, 'public.html'));
fs.mkdirSync(path.join(out, 'public'), { recursive: true });
fs.copyFileSync('public.html', path.join(out, 'public', 'index.html'));
if (fs.existsSync('.well-known')) fs.cpSync('.well-known', path.join(out, '.well-known'), { recursive: true });
if (fs.existsSync('icons')) fs.cpSync('icons', path.join(out, 'icons'), { recursive: true });
fs.mkdirSync(path.join(out, 'assets'), { recursive: true });
const latestAsset = 'app.secured.js';
const latestPath = path.join('assets', latestAsset);
if (!fs.existsSync(latestPath)) throw new Error(`${latestAsset} manquant`);
fs.copyFileSync(latestPath, path.join(out, 'assets', latestAsset));
console.log('PicoTrack build : asset courant + portail public (/public et /public.html) publiés.');
