-- Schéma public PicoTrack relevé en LECTURE SEULE le 9 oct. 2026 à 01:50 (Paris)
-- via information_schema.columns, sans aucune donnée. Identique sur EFC (jcanufkmcslxwmheqccp)
-- et sur la démo (ukucbfxyvyvtlglujoht). Colonnes, types, NULL et défauts seulement
-- (pas d'index, contraintes, RLS ni fonctions).
create table active_device_sessions (id uuid not null default gen_random_uuid(), user_id uuid not null, email text, environment_code text not null, license_type text not null, session_token text not null, user_agent text, created_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), revoked_at timestamptz, revoke_reason text);
create table app_roles (id uuid not null default gen_random_uuid(), tenant_id uuid, environment_code text not null, name text not null, permissions jsonb default '{}'::jsonb, active boolean default true, created_at timestamptz default now(), description text default '', updated_at timestamptz default now());
create table appointments (id uuid not null default gen_random_uuid(), form_id bigint, field_id text, response_id bigint, title text, customer_name text, date date not null, start_time time not null, end_time time not null, status text default 'confirmed', assigned_team text, capacity_group text, created_at timestamptz default now(), updated_at timestamptz default now(), capacity_limit integer default 1, parallel_slots integer default 1, tenant_id uuid, environment_code text not null default 'DEMO');
create table database_rows (id bigserial not null, database_id text not null, environment_code text not null default 'DEMO', source text, form_id text, submission_id text, "values" jsonb default '{}'::jsonb, created_at timestamptz default now(), tenant_id uuid);
create table databases (id text not null, environment_code text not null default 'DEMO', nom text not null, couleur text, type text default 'manual', columns jsonb default '[]'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), tenant_id uuid);
create table environment_license_limits (id bigserial not null, environment_code text not null, supervision_limit integer default 0, pad_limit integer default 0, lecture_limit integer default 0, updated_at timestamptz default now(), tenant_id uuid);
create table forms (id bigserial not null, nom text not null, description text default '', couleur text default '#3b82f6', actif boolean default true, modules text[] default '{}', fields jsonb default '[]'::jsonb, created_at timestamptz default now(), visible_roles jsonb default '[]'::jsonb, triggers jsonb default '{}'::jsonb, version integer default 1, published boolean default true, tenant_id uuid, environment_code text not null default 'DEMO', permissions jsonb not null default '{"edit": [], "view": [], "delete": [], "submit": []}'::jsonb);
create table licenses (id bigserial not null, environment_code text not null, license_key text not null, license_type text not null default 'nomade', label text, active boolean default true, device_name text, last_seen timestamptz, created_at timestamptz default now(), email text default '', password_hash text default '', role text default 'pad_user', scope text default 'environment', roles jsonb default '[]'::jsonb);
create table mail_logs (id bigserial not null, environment_code text not null default 'DEMO', source text not null default 'picotrack', source_id text, recipient text, subject text, status text not null default 'created', provider_id text, error text, created_at timestamptz not null default now());
create table service_instances (id bigserial not null, service_id bigint, ref text, form_data jsonb default '{}'::jsonb, status_id text default '', priority text default 'normal', events jsonb default '[]'::jsonb, device text default 'desktop', created_at timestamptz default now(), updated_at timestamptz default now(), tenant_id uuid, assigned_to text, environment_code text not null default 'DEMO', created_by text, current_status_id text, reference text, submission_id bigint);
create table services (id bigserial not null, nom text not null, description text default '', couleur text default '#3b82f6', actif boolean default true, statuses jsonb default '[]'::jsonb, actions jsonb default '[]'::jsonb, created_at timestamptz default now(), form_id bigint, id_pattern text default 'SVC-{YYYY}-{0000}', flux jsonb default '[]'::jsonb, card_config jsonb default '{}'::jsonb, kanban_groups jsonb default '[]'::jsonb, tenant_id uuid, environment_code text not null default 'DEMO', permissions jsonb not null default '{"edit": [], "view": [], "create": [], "delete": []}'::jsonb);
create table submissions (id bigserial not null, form_id bigint, "values" jsonb default '{}'::jsonb, device text default 'desktop', created_at timestamptz default now(), tenant_id uuid, environment_code text not null default 'DEMO');
create table tenants (id uuid not null default gen_random_uuid(), nom text not null, code text not null, plan text default 'starter', actif boolean default true, created_at timestamptz default now(), logo_url text, couleur text default '#059669', max_supervision integer default 3, max_pad integer default 10, supa_url text, supa_key text);
create table user_profiles (id uuid not null, email text not null, role text not null default 'client_admin', environment_code text not null default 'GLOBAL', active boolean default true, created_at timestamptz default now(), tenant_id uuid, label text, firstname text, lastname text, license_key text, password_hash text, roles jsonb default '[]'::jsonb, scope text default 'environment', updated_at timestamptz default now(), login_user text, first_name text, last_name text, username text, license_type text, resolved_permissions jsonb default '{}'::jsonb);
